-- Secuencias en oracle
CREATE SEQUENCE SECUENCIA1
START WITH 10
INCREMENT BY 50
MAXVALUE 300
NOCACHE
NOCYCLE;

SELECT SECUENCIA1.NEXTVAL FROM DUAL;

-- UNA SECUENCIA EN ORACLE ES UN OBJECTO DE INCREMENTO NUMERAL.

CREATE SEQUENCE SECUENCIA2
START WITH 10
INCREMENT BY 50
MAXVALUE 300
NOCACHE
CYCLE;

SELECT SECUENCIA2.NEXTVAL FROM DUAL;

CREATE TABLE EJEMPLO
(CODIGO NUMBER DEFAULT SECUENCIA2.NEXTVAL PRIMARY KEY,
NOMBRE VARCHAR2(30));

INSERT INTO EJEMPLO(NOMBRE) VALUES ('YYYYYYY');

SELECT * FROM EJEMPLO;

INSERT INTO EJEMPLO(NOMBRE) VALUES ('XXXXXX');

CREATE TABLE EJEMPLO2
(CODIGO NUMBER DEFAULT SECUENCIA2.NEXTVAL PRIMARY KEY,
NOMBRE VARCHAR2(30));

INSERT INTO EJEMPLO2(NOMBRE) VALUES ('CCCCCCCCC');

SELECT * FROM EJEMPLO2;

SELECT SECUENCIA2.CURRVAL FROM DUAL;

CREATE SEQUENCE SECUENCIA3
START WITH 100
INCREMENT BY -20
MAXVALUE 100
MINVALUE 10
NOCYCLE
NOCACHE;

SELECT SECUENCIA3.NEXTVAL FROM DUAL;

CREATE SEQUENCE SECUENCIA4
START WITH 100
INCREMENT BY -20
MAXVALUE 100
MINVALUE 10
CYCLE
NOCACHE;

SELECT SECUENCIA4.NEXTVAL FROM DUAL;

INSERT INTO EJEMPLO2(NOMBRE) VALUES ('OOOOOOOOO');

ROLLBACK;

CREATE SEQUENCE SECUENCIA5
START WITH 10
INCREMENT BY 50
MAXVALUE 300
CACHE 4
CYCLE;

SELECT SECUENCIA5.NEXTVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE SECUENCIA6
START WITH 2
INCREMENT BY 2
MAXVALUE 300
CACHE 4
CYCLE;

SELECT SECUENCIA5.NEXTVAL FROM DUAL;

CREATE SEQUENCE SECUENCIA7
START WITH 2
INCREMENT BY 2
CACHE 4
CYCLE;

SELECT SECUENCIA7.NEXTVAL FROM DUAL;

-- INDICES

-- Linea que permite realizar operaciones de usuario
ALTER SESSION SET "_oracle_script" = true;

CREATE TABLE PRODUCTO
(CODIGO NUMBER PRIMARY KEY,
NOMBRE VARCHAR(30),
PRECIO NUMBER);

INSERT ALL
INTO PRODUCTO VALUES (1,'JABON',500)
INTO PRODUCTO VALUES (2,'YOGURT',600)
INTO PRODUCTO VALUES (3,'PLATANO',800)
SELECT * FROM DUAL;

SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'PRODUCTO';

-- ALL_IND_COLUMNS

DESC ALL_IND_COLUMNS;

SELECT *FROM USER_IND_COLUMNS;

-- CREAR UN INDICE DE TIPO UNICO

CREATE UNIQUE INDEX UN_NOMBRE ON PRODUCTO(NOMBRE);

INSERT INTO PRODUCTO VALUES (4,'JABON',900); -- NO INSERTA NO SE PERMITE VALORES REPETIDOS
INSERT INTO PRODUCTO VALUES (5,'MARIAJUANA',1000); -- SI INSERTA
INSERT INTO PRODUCTO VALUES (4,'JABON REY',900); -- INSERTA HAY CAMBIO EN EL NOMBRE

CREATE INDEX IN_PRECIO ON PRODUCTO(PRECIO);

SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'PRODUCTO';

INSERT INTO PRODUCTO VALUES (4,'JABON REY',900);

ALTER TABLE PRODUCTO ADD CATEGORIA NUMBER; 
ALTER TABLE PRODUCTO ADD MARCA VARCHAR(30);

CREATE BITMAP INDEX BM_CATEGORIA ON PRODUCTO(CATEGORIA);

CREATE INDEX NO_MARCA ON PRODUCTO(MARCA);

SELECT * FROM PRODUCTO
WHERE MARCA = 'APINA';

-- INDICES VASADO EN FUNCIONES

SELECT * FROM PRODUCTO
WHERE LOWER(MARCA) = 'COLANTA';

CREATE INDEX MARCA_MINUSCULA ON PRODUCTO(LOWER(MARCA));